#!/usr/bin/env python3
"""Deterministically regenerate the E274 arithmetic kernel certificates.

The default mode is read-only: the generated bytes are compared with the 18
checked-in ``ArithmeticSearchCertificateD0`` through ``D17`` modules.  Files
are changed only with ``--write``.

This generator intentionally mirrors the executable definitions in
``ErdosProblems/E274/ArithmeticSearch.lean`` rather than treating the existing
certificate theorem statements as input.  In particular, it uses exact
integer residuals, the same denominator interval, the same pairwise-GCD guard,
and the four source-shaped obstruction detectors.  Terminal branches are
discharged directly by proof-producing ``decide +kernel``.  Every nonterminal
branch unfolds exactly one search step, checks only its concrete admissible
denominator filter with ``decide +kernel``, and rewrites the resulting child
calls with the imported next-depth certificates.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import difflib
from fractions import Fraction
import hashlib
from itertools import combinations
import json
from math import gcd
from pathlib import Path
import sys
from typing import Iterable


TOTAL_TERMS = 17
EXPECTED_DEPTH_COUNTS = (
    1,
    15,
    43,
    88,
    109,
    89,
    63,
    54,
    53,
    54,
    50,
    38,
    35,
    36,
    46,
    74,
    199,
    5,
)
EXPECTED_TOTAL_STATES = 1052
EXPECTED_SURVIVORS_SHA256 = (
    "0244dcaa451200177fe26b8ea2b8ab53f3737817004129afbd9969e1bead2d57"
)
EXPECTED_SURVIVORS = (
    (4, 6, 8, 12, 16, 18, 24, 30, 32, 36, 40, 42, 48, 54, 56, 60, 4320),
    (4, 6, 8, 12, 16, 18, 24, 30, 32, 36, 40, 42, 48, 56, 60, 64, 320),
    (4, 6, 8, 12, 16, 18, 24, 30, 32, 36, 40, 42, 48, 56, 60, 80, 160),
    (4, 6, 8, 12, 16, 18, 24, 30, 32, 36, 40, 42, 48, 56, 60, 96, 120),
    (4, 6, 8, 12, 16, 18, 24, 30, 32, 36, 40, 42, 48, 56, 72, 90, 96),
)


@dataclass(frozen=True)
class SearchState:
    """One call of Lean's ``searchIndexLists`` at total depth seventeen."""

    left: int
    num: int
    den: int
    previous: int
    prefix_rev: tuple[int, ...]

    @property
    def depth(self) -> int:
        return TOTAL_TERMS - self.left


def pairwise_coprime(values: Iterable[int]) -> bool:
    values_tuple = tuple(values)
    return all(gcd(a, b) == 1 for a, b in combinations(values_tuple, 2))


def canonical_sha256(values: Iterable[tuple[int, ...]]) -> str:
    payload = json.dumps(tuple(sorted(values)), separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def contains_p42(values: tuple[int, ...]) -> bool:
    halves = tuple(value // 2 for value in values if value % 2 == 0)
    return any(pairwise_coprime(parts) for parts in combinations(halves, 3))


def contains_p43(values: tuple[int, ...]) -> bool:
    thirds = tuple(value // 3 for value in values if value % 3 == 0)
    return any(pairwise_coprime(parts) for parts in combinations(thirds, 4))


def contains_p45(values: tuple[int, ...]) -> bool:
    twice_odd = tuple(value // 2 for value in values if value % 4 == 2)
    quarters = tuple(value // 4 for value in values if value % 4 == 0)
    return any(
        pairwise_coprime((r1,) + parts)
        for r1 in twice_odd
        for parts in combinations(quarters, 3)
    )


def contains_p47(values: tuple[int, ...]) -> bool:
    if 3 not in values:
        return False
    three_odd = tuple(
        value // 3 for value in values if value != 3 and value % 6 == 3
    )
    sixths = tuple(value // 6 for value in values if value % 6 == 0)
    return any(
        pairwise_coprime((r2,) + parts)
        for r2 in three_odd
        for parts in combinations(sixths, 3)
    )


def contains_published_obstruction(values: tuple[int, ...]) -> bool:
    return (
        contains_p42(values)
        or contains_p43(values)
        or contains_p45(values)
        or contains_p47(values)
    )


def admissible_next(prefix_rev: tuple[int, ...], denominator: int) -> bool:
    if any(gcd(denominator, old) <= 1 for old in prefix_rev):
        return False
    source_order = tuple(reversed((denominator,) + prefix_rev))
    return not contains_published_obstruction(source_order)


def enumerate_certificate_tree(
    root: SearchState,
) -> tuple[
    tuple[tuple[int, ...], ...],
    tuple[tuple[SearchState, ...], ...],
    dict[SearchState, tuple[tuple[int, ...], ...]],
]:
    """Enumerate every recursive state and its exact subtree output."""

    states_by_depth: list[list[SearchState]] = [
        [] for _ in range(TOTAL_TERMS + 1)
    ]
    outputs: dict[SearchState, tuple[tuple[int, ...], ...]] = {}

    def visit(state: SearchState) -> tuple[tuple[int, ...], ...]:
        if not 0 <= state.depth <= TOTAL_TERMS:
            raise AssertionError(f"invalid search depth: {state}")
        states_by_depth[state.depth].append(state)

        if state.left == 0:
            result = (
                (tuple(reversed(state.prefix_rev)),) if state.num == 0 else ()
            )
            outputs[state] = result
            return result
        if state.num == 0:
            outputs[state] = ()
            return ()

        lower = max(
            state.previous + 1,
            (state.den + state.num - 1) // state.num,
        )
        if state.previous == 0:
            lower = max(3, lower)
        upper = (state.left * state.den) // state.num

        result_list: list[tuple[int, ...]] = []
        for denominator in range(lower, upper + 1):
            if not admissible_next(state.prefix_rev, denominator):
                continue
            raw_num = state.num * denominator - state.den
            raw_den = state.den * denominator
            common = gcd(raw_num, raw_den)
            child = SearchState(
                left=state.left - 1,
                num=raw_num // common,
                den=raw_den // common,
                previous=denominator,
                prefix_rev=(denominator,) + state.prefix_rev,
            )
            result_list.extend(visit(child))

        result = tuple(result_list)
        outputs[state] = result
        return result

    root_output = visit(root)
    return (
        root_output,
        tuple(tuple(states) for states in states_by_depth),
        outputs,
    )


def validate_tree(
    root_output: tuple[tuple[int, ...], ...],
    states_by_depth: tuple[tuple[SearchState, ...], ...],
    outputs: dict[SearchState, tuple[tuple[int, ...], ...]],
) -> None:
    """Fail closed if the regenerated tree is not the frozen certificate tree."""

    depth_counts = tuple(len(states) for states in states_by_depth)
    if depth_counts != EXPECTED_DEPTH_COUNTS:
        raise AssertionError(
            f"depth counts changed: {depth_counts} != {EXPECTED_DEPTH_COUNTS}"
        )
    if sum(depth_counts) != EXPECTED_TOTAL_STATES:
        raise AssertionError(
            f"state count changed: {sum(depth_counts)} != {EXPECTED_TOTAL_STATES}"
        )
    flattened = tuple(state for states in states_by_depth for state in states)
    if len(set(flattened)) != EXPECTED_TOTAL_STATES:
        raise AssertionError("the regenerated tree contains duplicate states")
    if len(outputs) != EXPECTED_TOTAL_STATES:
        raise AssertionError("not every regenerated state received an output")
    if root_output != EXPECTED_SURVIVORS:
        raise AssertionError("the root output is not the frozen five survivors")
    if canonical_sha256(root_output) != EXPECTED_SURVIVORS_SHA256:
        raise AssertionError("the root-output SHA-256 is not the frozen digest")

    terminal_successes = tuple(
        state
        for state in states_by_depth[TOTAL_TERMS]
        if state.num == 0 and outputs[state]
    )
    if len(terminal_successes) != len(EXPECTED_SURVIVORS):
        raise AssertionError(
            "successful terminal count changed: "
            f"{len(terminal_successes)} != {len(EXPECTED_SURVIVORS)}"
        )

    for depth, states in enumerate(states_by_depth):
        for state in states:
            if state.depth != depth:
                raise AssertionError(f"state placed at wrong depth: {state}")
            if len(state.prefix_rev) != depth:
                raise AssertionError(f"prefix length mismatch: {state}")
            expected_previous = state.prefix_rev[0] if state.prefix_rev else 0
            if state.previous != expected_previous:
                raise AssertionError(f"previous denominator mismatch: {state}")
            source_order = tuple(reversed(state.prefix_rev))
            if any(a >= b for a, b in zip(source_order, source_order[1:])):
                raise AssertionError(f"prefix is not strictly increasing: {state}")
            residual = Fraction(1) - sum(
                (Fraction(1, denominator) for denominator in source_order),
                Fraction(0),
            )
            if residual != Fraction(state.num, state.den):
                raise AssertionError(f"residual mismatch: {state}")


def format_list(values: Iterable[int]) -> str:
    return "[" + ", ".join(str(value) for value in values) + "]"


def format_survivors(values: Iterable[tuple[int, ...]]) -> str:
    return "[" + ", ".join(format_list(value) for value in values) + "]"


def theorem_block(
    depth: int,
    theorem_index: int,
    state: SearchState,
    output: tuple[tuple[int, ...], ...],
) -> str:
    if state.left == 0:
        return (
            "set_option maxRecDepth 1000000 in\n"
            "set_option maxHeartbeats 0 in\n"
            f"@[simp] theorem arithmeticCertD{depth}_{theorem_index} :\n"
            f"    searchIndexLists {state.left} {state.num} {state.den} "
            f"{state.previous} {format_list(state.prefix_rev)} =\n"
            f"      {format_survivors(output)} := by\n"
            "  decide +kernel\n"
        )

    lower = max(
        state.previous + 1,
        (state.den + state.num - 1) // state.num,
    )
    if state.previous == 0:
        lower = max(3, lower)
    upper = (state.left * state.den) // state.num
    range_count = max(0, upper + 1 - lower)
    admissible_denominators = tuple(
        denominator
        for denominator in range(lower, upper + 1)
        if admissible_next(state.prefix_rev, denominator)
    )

    return (
        "set_option maxRecDepth 1000000 in\n"
        "set_option maxHeartbeats 0 in\n"
        f"@[simp] theorem arithmeticCertD{depth}_{theorem_index} :\n"
        f"    searchIndexLists {state.left} {state.num} {state.den} "
        f"{state.previous} {format_list(state.prefix_rev)} =\n"
        f"      {format_survivors(output)} := by\n"
        "  rw [searchIndexLists]\n"
        "  change\n"
        f"    (List.range' {lower} {range_count}).flatMap (fun d =>\n"
        f"      if admissibleNext {format_list(state.prefix_rev)} d then\n"
        f"        let rawNum := {state.num} * d - {state.den}\n"
        f"        let rawDen := {state.den} * d\n"
        "        let common := Nat.gcd rawNum rawDen\n"
        f"        searchIndexLists {state.left - 1} "
        "(rawNum / common) (rawDen / common) d\n"
        f"          (d :: {format_list(state.prefix_rev)})\n"
        f"      else []) = {format_survivors(output)}\n"
        "  rw [flatMap_if_eq_filter_flatMap]\n"
        "  have hfilter :\n"
        f"      (List.range' {lower} {range_count}).filter\n"
        f"        (admissibleNext {format_list(state.prefix_rev)}) =\n"
        f"        {format_list(admissible_denominators)} := by\n"
        "    decide +kernel\n"
        "  rw [hfilter]\n"
        "  norm_num\n"
    )


def standard_module(
    depth: int,
    import_target: str,
    indexed_states: Iterable[tuple[int, SearchState]],
    outputs: dict[SearchState, tuple[tuple[int, ...], ...]],
) -> str:
    description = (
        "Kernel-reducible branch certificate for the exact E274 "
        "length-seventeen arithmetic search."
    )
    blocks = "\n".join(
        theorem_block(depth, theorem_index, state, outputs[state])
        for theorem_index, state in indexed_states
    )
    return (
        f"import ErdosProblems.E274.{import_target}\n\n"
        f"/-! {description} -/\n\n"
        "namespace ErdosProblems.E274\n\n"
        f"{blocks}"
        "\nend ErdosProblems.E274\n"
    )


def render_files(
    states_by_depth: tuple[tuple[SearchState, ...], ...],
    outputs: dict[SearchState, tuple[tuple[int, ...], ...]],
) -> dict[str, bytes]:
    """Render the 18 depth modules D0 through D17."""

    rendered: dict[str, bytes] = {}
    for depth in range(0, TOTAL_TERMS):
        states = tuple(enumerate(states_by_depth[depth]))
        module = standard_module(
            depth,
            f"ArithmeticSearchCertificateD{depth + 1}",
            states,
            outputs,
        )
        if depth == 0:
            module = module.replace(
                "end ErdosProblems.E274\n",
                "theorem checked_seventeen_survivors :\n"
                "    candidateIndexLists 17 = seventeenSurvivors := by\n"
                "  unfold candidateIndexLists\n"
                "  rw [arithmeticCertD0_0]\n"
                "  rfl\n\n"
                "end ErdosProblems.E274\n",
            )
        rendered[f"ArithmeticSearchCertificateD{depth}.lean"] = module.encode()

    depth_seventeen = tuple(enumerate(states_by_depth[TOTAL_TERMS]))
    rendered["ArithmeticSearchCertificateD17.lean"] = standard_module(
        TOTAL_TERMS,
        "ArithmeticSearch",
        depth_seventeen,
        outputs,
    ).encode()
    return rendered


def first_diff(expected: bytes, actual: bytes, path: Path) -> str:
    expected_text = expected.decode("utf-8", errors="replace").splitlines()
    actual_text = actual.decode("utf-8", errors="replace").splitlines()
    return "\n".join(
        difflib.unified_diff(
            actual_text,
            expected_text,
            fromfile=str(path),
            tofile=f"generated:{path.name}",
            n=2,
        )
    )


def synchronize(
    target_directory: Path,
    rendered: dict[str, bytes],
    *,
    write: bool,
) -> tuple[int, int]:
    """Compare or explicitly update generated modules; return match/change counts."""

    matched = 0
    changed = 0
    mismatches: list[str] = []
    for name in sorted(rendered):
        path = target_directory / name
        expected = rendered[name]
        actual = path.read_bytes() if path.exists() else b""
        if actual == expected:
            matched += 1
            continue
        changed += 1
        if write:
            path.write_bytes(expected)
        else:
            reason = "missing" if not path.exists() else "byte mismatch"
            diff = first_diff(expected, actual, path)
            mismatches.append(f"{path}: {reason}\n{diff}")

    expected_names = set(rendered)
    existing_names = {
        path.name
        for path in target_directory.glob("ArithmeticSearchCertificateD*.lean")
    }
    extras = sorted(existing_names - expected_names)
    if extras:
        mismatches.append(
            "unexpected certificate modules (never deleted automatically): "
            + ", ".join(extras)
        )

    if mismatches and not write:
        raise RuntimeError("\n\n".join(mismatches))
    if extras and write:
        raise RuntimeError(
            "--write updated known modules but unexpected modules remain: "
            + ", ".join(extras)
        )
    return matched, changed


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="read-only byte comparison (the default)",
    )
    mode.add_argument(
        "--write",
        action="store_true",
        help="explicitly replace mismatching generated certificate modules",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[2]
    target_directory = repo_root / "ErdosProblems" / "E274"
    root = SearchState(TOTAL_TERMS, 1, 1, 0, ())

    root_output, states_by_depth, outputs = enumerate_certificate_tree(root)
    validate_tree(root_output, states_by_depth, outputs)
    rendered = render_files(states_by_depth, outputs)

    try:
        matched, changed = synchronize(
            target_directory,
            rendered,
            write=args.write,
        )
    except RuntimeError as error:
        print(f"generate_arithmetic_kernel_certificates: FAIL\n{error}", file=sys.stderr)
        return 1

    mode = "WRITE" if args.write else "CHECK"
    depth_counts = tuple(len(states) for states in states_by_depth)
    print(
        "generate_arithmetic_kernel_certificates: PASS "
        f"mode={mode} states={sum(depth_counts)} "
        f"depth_counts={list(depth_counts)} terminals={len(states_by_depth[-1])} "
        f"survivors={len(root_output)} files={len(rendered)} "
        f"root_sha256={canonical_sha256(root_output)} "
        f"matched={matched} changed={changed}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
